name: Build and Test Smart Contracts
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v3
      - name: Show filesystem
        working-directory: examples/hello
        run: |
           pwd
           ls -la
           find
      - name: Build hello contract
        uses: ./actions/action-cargo
        with:
          cargo-cmd: cargo contract build
          working-directory: examples/hello
      # - name: Test hello contract with cargo contract test
      #   uses: ./actions/action-cargo
      #   with:
      #     cargo-cmd: cargo contract test
      #     working-directory: examples/hello
      # - name: Test hello contract with cargo test
      #   uses: ./actions/action-cargo
      #   with:
      #     cargo-cmd: cargo test
      #     working-directory: examples/hello
      # - uses: ./actions/action-cargo
      #   with:
      #     cargo-cmd: versions.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
             toolversions
             target/ink/**/*.contract
